CREATE DATABASE IF NOT EXISTS pharmaflow;
USE pharmaflow;
CREATE TABLE IF NOT EXISTS users (
 id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, email VARCHAR(160) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role ENUM('CUSTOMER','PHARMACIST','ADMIN') NOT NULL DEFAULT 'CUSTOMER', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS categories (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS medicines (
 id INT PRIMARY KEY AUTO_INCREMENT, category_id INT, name VARCHAR(160) NOT NULL, generic_name VARCHAR(160), manufacturer VARCHAR(160), description TEXT,
 price DECIMAL(10,2) NOT NULL, stock INT NOT NULL DEFAULT 0, prescription_required BOOLEAN DEFAULT FALSE, image_url VARCHAR(500), active BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES categories(id)
);
CREATE TABLE IF NOT EXISTS prescriptions (
 id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500), ocr_text TEXT, status ENUM('PENDING','OCR_REVIEW','APPROVED','REJECTED') DEFAULT 'PENDING', pharmacist_note TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, verified_at TIMESTAMP NULL, FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS orders (
 id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, prescription_id INT NULL, status ENUM('PENDING','CONFIRMED','PACKED','SHIPPED','DELIVERED','CANCELLED') DEFAULT 'PENDING', payment_status ENUM('PENDING','PAID','FAILED','COD') DEFAULT 'PENDING', total DECIMAL(10,2) NOT NULL DEFAULT 0, address TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(prescription_id) REFERENCES prescriptions(id)
);
CREATE TABLE IF NOT EXISTS order_items (
 id INT PRIMARY KEY AUTO_INCREMENT, order_id INT NOT NULL, medicine_id INT NOT NULL, quantity INT NOT NULL, unit_price DECIMAL(10,2) NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY(medicine_id) REFERENCES medicines(id)
);
CREATE TABLE IF NOT EXISTS reminders (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, medicine_name VARCHAR(160) NOT NULL, next_refill_date DATE NOT NULL, active BOOLEAN DEFAULT TRUE, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE INDEX idx_medicines_name ON medicines(name);
CREATE INDEX idx_orders_user ON orders(user_id, created_at);
CREATE INDEX idx_prescriptions_status ON prescriptions(status);
